<?php


namespace App\Model\Table;


use Cake\ORM\Table;

class CouponTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');
        $this->hasOne('Order_detail')
            ->setName('coupon')
            ->setDependent(true);
    }
}
