<?php


namespace App\Model\Table;


use Cake\ORM\Table;

class DeliveryTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');
    }
}
