<?php


namespace App\Model\Table;


use Cake\Datasource\ConnectionManager;
use Cake\ORM\Table;
use Cake\ORM\TableRegistry;

class OrderTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->hasOne('Order_detail')
            ->setName('order_detail')
            ->setDependent(true);
        $this->addBehavior('Timestamp');
    }

    public function getOrderInfo() {
        $conn = ConnectionManager::get('default');
        $query = $conn->execute('SELECT order.name, `order`.description, order_detail.prices, order_detail.tax_prices, coupon.description AS ly_do_giam, delivery.decription AS  name_delivery, payemnt_method.name AS name_payment, coupon.prices AS gia_giam, order_detail.status, order.id
FROM `order`
INNER JOIN order_detail ON order_detail.order_id = order.id
INNER JOIN coupon ON coupon.id = order_detail.coupon_id
INNER JOIN delivery ON delivery.id = order_detail.delivery_id
INNER JOIN payemnt_method ON payemnt_method.id = order_detail.delivery_id
WHERE `order`.`disable` = 0');
        return $query->fetchAll('assoc');
    }

    public function delete_order($id) {
        $orderTable = TableRegistry::get('Order');

        $orderTable = TableRegistry::getTableLocator()->get('Order');
        $order = $orderTable->get($id);

        $order->disable = 1;
        $order->update_date = date('Y-m-d H:i:s');
        return $orderTable->save($order);
    }

    public function insertOrder($data) {
        $orderTable = TableRegistry::getTableLocator()->get('Order');
        // insert information Order
        $orderdata = TableRegistry::getTableLocator()->get('Order')->newEntity([
            'name' => $data['name_product'],
            'description' => $data['description'],
            'id' => $data['order_id'],
            'update_date' => date('Y-m-d H:i:s'),
        ]);
        return $order = $orderTable->save($orderdata);
    }

    public function insertOrderDetail($param) {
        $orderDetailTable = TableRegistry::getTableLocator()->get('Order_detail');
        $query = TableRegistry::getTableLocator()->get('Order_detail')
            ->find()
            ->where(['order_id =' => $param['order_id']]);

        foreach ($query as $key => $order_detail) {
            $data = $order_detail;
        }
        $Orderdetail = TableRegistry::getTableLocator()->get('Order_detail')->newEntity([
            'status' => $param['tinh_trang'],
            'id' => $data->id,
            'update_date' => date('Y-m-d H:i:s')
        ]);
        // insert information Order Detail
        return $orderDetailTable = $orderDetailTable->save($Orderdetail);
    }
}
