<?php


namespace App\Model\Table;


use Cake\ORM\Table;

class OrderDetailTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');
        $this->addAssociations([
            'belongsTo' => [
                'Order' => ['className' => 'App\Model\Table\OrderTable']
            ],
            'hasOne' => ['Coupon'],
            'hasOne' => ['Delivery'],
            'hasOne' => ['PaymentMethod'],
        ]);
    }
}
